name: Deploy React with Docker to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Construye imagen solo con etapa builder
        run: docker build --target builder -t react-builder .

      - name: Extrae la carpeta build del contenedor
        run: |
          container_id=$(docker create react-builder)
          docker cp $container_id:/app/build ./build
          docker rm $container_id

      - name: Publica en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
